### ISSUE TITLE
Forge Port?

### ISSUE THREAD

**Issue by studkid** [andyvanee/hscroll#2]
Would there by chance be any plans on porting this mod to Forge instead of being exclusive to Fabric?  I personally play modded minecraft all the time and for me, Forge is the superior mod loader for me as it has all the mods I want to play on that over Fabric.  I'm not sure the exactly how much more difficult it would be to port over to Forge, but it would be really nice to be able to have a version available for both mod loaders (especially considering some mods I have played with require you to be able to shift scroll to use them to it's fullest potential).

**Comment by andyvanee** [comment]
To be honest, I didn't really expect this issue to persist this long, so I thought this mod would be archived by now 😞 

I'm not familiar with the Forge API at all, but I'm sure it's possible. I have no idea if the fixes would be compatible with other mods though...

Off the top of my head, I believe "Mouse Tweaks" or "Inventory Tweaks" adds some scroll wheel behaviors to the inventory screen, and I'm pretty sure those would have totally separate mouse handling code.

Can you let me know what mods specifically require shift scrolling?

Thanks!

**Comment by studkid** [comment]
From what I've seen in most mods where a shift scroll is used as an input, they usually use the crouch button + scroll wheel, it's just hard to change that muscle memory after being so used to it.  The main mod I have ran into so far (just because I haven't touched much modded in 1.13+ yet) is Dank Storage.  Essentially you can store many items in it like a backpack mod and in construction mod you can use the items directly from it.  Swapping items it directly tied to holding crouch and scroll wheel (and I was able to test this by changing crouch to 'z').

Other mods I know have a crouch + scroll wheel input, but not something I have tested myself post 1.13 is with Draconic Evolution's advanced dislocator and EnderIO with it's yeta wrench to toggle pipe visibility.  I feel like there are others as well, but for the most part I think these should at least be fixable by fixing the scroll wheel input for the inventory.

I still can't believe that Mojang still hasn't addressed this issue though.  It's been there since 1.13's launch, I would've hoped they would have fixed it in at least 1.15 in it's big list of bug fixes but I guess not.

**Comment by studkid** [comment]
I was messing around with this for the past few days and it seems like everything should be easily translatable from fabric to forge.  I haven't messed with 1.16 at all yet (since I was focusing on 1.15.2) but it sounds like mixin support is fully supported there without any other mod.  Pre 1.16 has [Mixin Bootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap) which seems to add all of the mixin support the Fabric uses, if not the exact same mixin support (since both seem to use spongepowered's implementation).

The only thing stopping me right now with it this though is that I can't tell if the mixin class is even running in game, and/or if 
I misinterpreted the mappings you were using (most notable ones being that `client.MinecraftClient` and `client.util.Window` which didn't exist for me.  I changed them to `client.Minecraft` and `client.MainWindow` respectively as they were the ones that seemed to make the most sense).  I will admit though I'm I definitely not a very experienced coder though, only really starting to learn java last year so maybe I'm just overlooking something.

**Comment by andyvanee** [comment]
Thanks for the details @studkid ! I don't have much experience when it comes to modding Minecraft either, but I've taken a quick look and found these, which may be relevant:

https://github.com/MinecraftForge/MinecraftForge/pull/6037

https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/client/MouseHelper.java.patch#L43

I seems to me that the *forge way* would probably be to hook into `onMouseScroll` or `onGuiMouseScrollPre`, pull out the relevant information, and somehow modify the event or dispatch a new event?
